# Generated by Django 5.2.6 on 2025-09-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id']},
        ),
    ]
